### ISSUE TITLE
Add Helical Coil Optimization Utilities

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#578]
- [x] Add python version of REGCOIL, along with tests #579
- [x] Add utility for finding helical coils from the output of python version of REGCOIL
  - [ ] expand utility to work for modular coils and saddle coils as well, or add new utilities (see #893 )
- [x] Add MagneticField class for magnetic field from a surface current potential #592 
- [x] add tutorial on coil design (using the regcoil and the utilities to create coils, checking vacuum flux surfaces, what helicity ratio is, etc)
