### ISSUE TITLE
Improving DESC Surface Boozer Transform

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#754]
While we wait on progress on #369 , there are a few improvements that can be made when using the surface transform in DESC
- [ ] Adding utility function to perform the transform in the most efficient way possible (reusing matrices etc), similar to what was done in #680 
- [x] Resolving #720 to make zernike evaluations faster - this issue was actually reverted though...
- [ ] changing the utility functions used in calculating the transform at multiple surfaces (like in `make_boozmn_output`) to use jax.numpy, which can allow for more parts of the calculation to be performed on the GPU and potentially allow jitting more parts of the calculation (like the `zernike_to_fourier` function, for example) #1197

**Comment by dpanici** [comment]
#369 maybe duplicate

**Comment by dpanici** [comment]
#680 should resolve this maybe

**Comment by f0uriest** [comment]
With @unalmis recent updates to grid tags, I think we could add a `requires_meshgrid` thing to the boozer qtys and then vmap them over rho, allowing you to do multiple surfaces at once.
